# Generated by Django 4.0.6 on 2022-07-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
