# Generated by Django 4.0.6 on 2022-07-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_comments_created_at_comments_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='created_at',
        ),
    ]
