# Generated by Django 4.0.6 on 2022-07-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField()),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_liked', to='Blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
