# Generated by Django 4.0.6 on 2022-07-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_likes_created_at_likes_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='Post',
            new_name='post',
        ),
    ]
